### ISSUE TITLE
Prepare for core C# change

### ISSUE THREAD

**Issue by michaelblyons** [michaelblyons/SublimeSyntax-HTML-CSharp#2]
When [the core C# rewrite](https://github.com/sublimehq/Packages/pull/93) is approved, double check that things still work.
### Known issues:
- [ ] The `<script runat="server">` blocks will need an additional embedded scope of `meta.class.body.cs`, and possibly also `meta.method.body.cs`.
  
  One of those is, after all, an accurate description of their scope. [According to ".NET Guy,"](http://discuss.joelonsoftware.com/default.asp?dotnet.12.409035.9) each `<script>` block is compiled into a corresponding method in the generated class. I am suspicious, though. I think that the access levels indicate that `<script>` blocks are nested directly in the class.

**Comment by gwenzek** [comment]
Note that a lot of scope renaming is going to take place, so don't start working on it too soon.
